language: python

python:
  - "2.7"

env:
  - DJANGO="https://www.djangoproject.com/download/1.6a1/tarball/"
  - DJANGO="django==1.5.1 --use-mirrors"

install:
  - pip install $DJANGO
  - python setup.py install

script:
  - python cloudfiles/runtests/runtests.py
