language: python

python:
  - "2.7"

env:
  - DJANGO="https://www.djangoproject.com/download/1.6a1/tarball/"
  - DJANGO="django==1.5.1 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install pyrax==1.4.5
  - pip install mock==1.0.1
  - python setup.py install

script: python runtests/runtests.py
